github/github-ds

script/console

This is me guessing, but I think with the rename (the last rename, and the really last rename) the console script didn't get updated to require the "github/ds" instead still requiring "github/kv" (which
also works).
This rewords that, the console still works (basically exactly the same as before) but it is slightly more correct.
So there, the world's most benign pull request.

Require the top library

---

.travis.yml
github-ds.gemspec

Fixes #7 by removing the gems `activerecord-mysql-adapter` and –through it– `mysql`. The latter has not been updated since 2013 and has long been replaced by `mysql2`.
With these changes, all tests pass.

Add and fix ruby 2.4.0 in travis builds, fixes #7

---

.gitignore
examples/example_setup.rb
examples/sql_with_connection.rb
lib/generators/github/ds/active_record_generator.rb
lib/generators/github/ds/templates/migration.rb
test/generators/github/store/active_record_generator_test.rb
test/test_helper.rb

Rails 5.1 was failing CI due to migrations now requiring a version. This adds the version to Rails version 5.x similar to how devise does it ([template](https://github.com/plataformatec/devise/blob/079ed3b6f8b671acde2dd630d28d21adb010fb3a/lib/generators/active_record/templates/migration.rb#L1), [generator](https://github.com/plataformatec/devise/blob/079ed3b6f8b671acde2dd630d28d21adb010fb3a/lib/generators/active_record/devise_generator.rb#L16)), [migration version](https://github.com/plataformatec/devise/blob/079ed3b6f8b671acde2dd630d28d21adb010fb3a/lib/generators/active_record/devise_generator.rb#L90-L94).
The downside is the migration file was being used in tests and examples (to avoid repeating myself) and now it can't be as easily (due to including erb). Now instead it uses the …

Rails 5.1 CI/Support

---

lib/github/result.rb
test/github/result_test.rb

It was returning false because the lack of a block would yield a local jump error which would then be rescued setting error and thus ok? to false.
Without the `if block_given?` check:
```
Failure:
GitHub::ResultTest#test_initialize_without_block [/Users/jnunemaker/github/github-ds/test/github/result_test.rb:88]:
Expected #<GitHub::Result:0x3fc6ca9bea80 error: #<LocalJumpError: no block given (yield)>> to be ok?.
```
With check the tests pass.

Make initialize without block return `true` for `ok?`

---

CHANGELOG.md
lib/github/ds/version.rb
lib/github/kv.rb
lib/github/sql.rb
test/github/kv_test.rb

This PR:
- Extends `GitHub::KV` to allow `SQL::Literal` values, this can be used to cast as binary literals `utf8mb4` strings, that otherwise would rise a warning in MySQL. A usage example wil could be 
```ruby
kv.set("key", SQL::BINARY( "🍻"))
```
- Fixes `GitHub::KV` to take into account that strings values can be of composed of multi-byte characters.
- Fixes the of error message in `validate_key_value_hash`
cc @jnunemaker @github/platform-data

Adds support for binary values in `GitHub::KV`

---

lib/github/sql.rb
test/github/sql_test.rb

This is a particularly subtle and hard to catch bug. `ensure` when used at the method definition level runs on every method call regardless of on early return. This means that when using `:force_timezone` and calling `results` more than once, the default_timezone was getting set to nil, because the second invocation would early return, not set the `zone` variable and thus set default_timezone to nil in the ensure block.

Scope `ensures` to only run if default_timezone actually altered

---

CHANGELOG.md
lib/github/ds/version.rb
lib/github/sql.rb
test/github/sql_test.rb

To add support for running queries inside an
`ActiveRecord::Base.transaction` scope.

Adds `SQL.transaction`

---

CHANGELOG.md
README.md
lib/github/ds.rb
lib/github/ds/version.rb
lib/github/kv.rb

This PR replaces `require` with `require_relative` to avoid requirement errors when the gem is required inside the a "gihub" load path in a rails application.
cc @jnunemaker @github/platform-data

Replace absolute `require` statements in favor of `require_relative`

---

CHANGELOG.md
lib/github/ds/version.rb
lib/github/sql.rb

Rails 4 changes the return type of `select_all` from `Array` to `ActiveRecord::Result`.
Calling `to_ary` on the `ActiveRecord::Result` returns the underlying array without having to make a copy. Calling `to_ary` on an `Array` (as would be the case on Rails 3.2) just returns the original array.
cc @jnunemaker @github/rails-upgrades

Ensure @hash_results is an array on rails 4

---

lib/github/sql.rb
test/github/sql_test.rb
test/test_helper.rb

This does a few minor things:
* encapsulates enforcing ActiveRecord.default_timezone into a single method
* moves usage of this method from `add` to `sanitize` (which is used by `interpolate` which is used by `add`). This is mostly a localization of the usage to where it is needed rather than the higher level spot around add. Should behave identical and makes it so `interpolate` can be used without worrying about timezone stuff being wrong.
* renames @forze_tz to @force_timezone which matches the hash option and is more descriptive.

Move Time Zone Forcing to sanitize

---

lib/github/sql.rb
lib/github/sql/errors.rb
lib/github/sql/literal.rb
lib/github/sql/rows.rb
test/github/sql_test.rb

This PR:
* allows passing methods to class `transaction` method similar to how rails does. Also documents the downside of class transaction method.
* adds instance transaction method for GitHub::SQL descendants that override connection. 
* moves errors, literal and rows to their own file for safe keeping.
* re-orders some methods based on their use. Higher level methods towards the top of the file and building blocks toward the bottom. Helps show priority a bit and puts more likely to change methods or those that you would want to understand and use toward the top.

Minor Tidying

---

README.md
docker-compose.yml
test/test_helper.rb

When making sure I didn't break anything on https://github.com/github/github-ds/pull/33, I had a bit of a hard time running the tests locally, so I added  a `docker-compose.yml` file to ease it up a bit.
It has the minor drawback of having to use a TCP connection to connect to MySQL, but I don't think it matters much for a test env

Add docker-compose file for ease of local testing

---

test/github/sql_test.rb

I started seeing failures locally for this test because locally I have STRICT_ALL_TABLES in my sql_mode.
Error:
```
$ script/test
bundle exec rake
+ bundle exec rake
create  db/migrate/20180302154356_create_key_values_table.rb
Run options: --seed 21062
................E
Error:
GitHub::SQLTest#test_affected_rows_even_when_query_generates_warning:
ActiveRecord::StatementInvalid: Mysql2::Error: Truncated incorrect DOUBLE value: '1x': UPDATE affected_rows_test SET x = x + 1 WHERE 1 = '1x'
```
The issue was that `1x` gets coerced to `1` when not in strict mode, but raises an error when in strict mode. According to my sql_mode for the session in tests strict was on:
```
p GitHub::SQL.results("SHOW VARIABLES LIKE 'sql_mode'")
```
I first went down the path of tweaking the sql_mode for the …

Make test_affected_rows_even_when_query_generates_warning less brittle

---

Gemfile
lib/github/kv.rb
test/generators/github/store/active_record_generator_test.rb
test/github/kv_test.rb

I recently needed an equivalent of the Redis `ttl` command in `GitHub::KV` and thought I'd open a PR here too in case we want to integrate it into `github-ds` instead of putting it in `lib/github/ds_extensions.rb`.

Add ttl command to return time of expiry

---

Gemfile
lib/github/sql.rb
test/github/sql_test.rb

Problem:
If a user passed duplicate column names to GitHub::DS, for example
`sql.add(SELECT id, NULL, NULL, name from repositories)` the valued
returned by `result` wouldn't line up with the column names. Instead
what would be returned is:
```
sql.results
[[1, nil, "repo name"], [2, nil, "repo name 2"]]
```
instead of the correct value set:
```
sql.results
[[1, nil, nil, "repo name"], [2, nil, nil, "repo name 2"]]
```
This is because we were calling `to_ary` on the
`ActiveRecord::Base#result`. This would loop through the columns and
rows and pair them up into a hash. The underlying problem is hashes
cannot contain keys with the same value, and Ruby will de-dup the keys
before retunring the result.
Solution: 
To fix this problem we can instead call `rows` on the returned results
which will …

Don't de-dup values in results array

---

.travis.yml
github-ds.gemspec
lib/github/kv.rb
test/github/kv_test.rb

This PR takes #42 and fixes the builds by uninstalling bundler 2 and installing a bundler less than 2. Bundler 2 doesn't support older versions of Ruby we need to test so we need to use the older one.
cc/ @dbussink @zerowidth

Fix binary encoding and bundler

---

lib/github/kv.rb
test/github/kv_test.rb

KV seems not to work well with timecop. For example
```ruby
now = Time.at(1556212894)
Timecop.freeze(now) do
GitHub.kv.set("foo", "bar", expires: now + 1.day)
GitHub.kv.get("foo")
#=> <GitHub::Result value: nil>
end
```
In this example, a KV value is set with an expiration in the past. When we try to look it up, the query is comparing the expiration to MySQL's `NOW()` function, which won't respect the time being frozen by Timecop.
This PR tries to solve this by passing in Ruby's `Time.now` to queries instead of relying on MySQL's `NOW()` function.

kv: Pass current time into queries

---

lib/github/sql.rb

Rails 7 has introduced a breaking change which removed mattr_accessor
methods in place of module instance methods
https://github.com/rails/rails/pull/42445

Ensure GitHub::SQL works on Rails 7

---

lib/github/sql.rb
test/github/sql_test.rb

This PR replaces `to_s(#{format.inspect})` with `to_formatted_s(#{format.inspect})`. `to_s` is deprecated in the latest [rails/rails 7.1.0.alpha.e8c0293](https://github.com/rails/rails/blob/a4d685b2842d91cb702259c07c50c2623288c714/activesupport/lib/active_support/core_ext/numeric/deprecated_conversions.rb).

Replace `(to_s#{format.inspect})` with `to_formatted_s(#{format.inspect})` as the former is deprecated for certain format conversions

---

lib/github/sql.rb

Frozen string literals might be a default thing in future Ruby versions (https://bugs.ruby-lang.org/issues/20205).
This PR fixes a tiny incompatibility in `sql.rb` where we have one instance of an empty string.

Call .dup on an empty string to get an non-frozen option

---

test/test_helper.rb

CI fix for `uninitialized constant ActiveSupport::LoggerThreadSafeLevel::Logger (NameError)` which happens because newer versions of Concurrent-Ruby removed a dependency on Logger but older versions of Rails aren't compatible with that.

[CI only] Explicitly require logger to fix Concurrent-Ruby removing the dependency
